// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnvtnkfeogufhjdomqol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudnRua2Zlb2d1ZmhqZG9tcW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjI0MjMsImV4cCI6MjA3MTQ5ODQyM30.SVCE9wB5npV981rMQq72Afl3-_Cktd4LH1MHH1tkFkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});